jobs:
  - name: nginx-manifest-1
    type: manifest
    steps:
    - IN: nginx-image-1
      pull: false
      switch: on
    - TASK: managed
      bump: patch
  - name: release-2
    type: release
    steps:
    - TASK: managed
      bump: patch
  - name: release-3
    type: release
    steps:
    - IN: version-2
    - IN: version-1
    - TASK: managed
      bump: patch
  - name: release-4
    type: release
    steps:
    - IN: docker-opts-1
      switch: on
    - IN: version-1
      versionNumber: 1000
    - TASK: managed
      bump: patch
  - name: nginx-manifest-2
    type: manifest
    steps:
    - IN: nginx-image-1
      pull: false
      switch: off
    - TASK: managed
      bump: patch
