jobs:
  - name: release-1
    type: release
    steps:
    - IN: docker-opts-1
      switch: on
    - IN: version-1
      versionNumber: 555
    - TASK: managed
      bump: patch
  - name: release-2
    type: release
    steps:
    - TASK: managed
      bump: patch
